### ISSUE TITLE
Package not installed

### ISSUE THREAD

**Issue by manualautomaton** [withtwoemms/sanka#21]
The package is missing when the distribution is installed. 

"~/.../site-packages/sanka-0.1.0.dist-info/" is the only artifact present after install so the source isn't routable and so leads to this sort of error:
```
ModuleNotFoundError: No module named 'sanka'
```

**Comment by withtwoemms** [comment]
slated for v0.1.2rc1 release. official release pending user acceptance.

**Comment by withtwoemms** [comment]
turns out v0.1.2rc2 did the trick
